// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQdRQZsNtl9OfPT6Fg_biz4lZhX4WneE',
    appId: '1:492205467828:web:1599a802512ff470e4cfe1',
    messagingSenderId: '492205467828',
    projectId: 'dapp-2b578',
    authDomain: 'dapp-2b578.firebaseapp.com',
    databaseURL: 'https://dapp-2b578-default-rtdb.firebaseio.com',
    storageBucket: 'dapp-2b578.appspot.com',
    measurementId: 'G-G5D36R3DH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdsIO26KUIlcjyGHG1XxgzIf-fIb6usk',
    appId: '1:492205467828:android:50296862fb200584e4cfe1',
    messagingSenderId: '492205467828',
    projectId: 'dapp-2b578',
    databaseURL: 'https://dapp-2b578-default-rtdb.firebaseio.com',
    storageBucket: 'dapp-2b578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9i_Ll-_o_WTZ1MEdVW0jfVPjOpoDXiJ0',
    appId: '1:492205467828:ios:c5727eee4867e4fbe4cfe1',
    messagingSenderId: '492205467828',
    projectId: 'dapp-2b578',
    databaseURL: 'https://dapp-2b578-default-rtdb.firebaseio.com',
    storageBucket: 'dapp-2b578.appspot.com',
    iosBundleId: 'com.example.realEstate',
  );
}
